# Generated by Django 4.0.5 on 2022-06-09 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='mobile',
            new_name='phone',
        ),
    ]
