# Generated by Django 4.0.5 on 2022-06-09 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(default='mayank', max_length=150),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(default='mayank', max_length=250),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(default='mayank', max_length=122),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(default='mayank', max_length=12),
        ),
    ]
